apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus-ingress-controller
  namespace: gatus-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus-ingress-controller
  template:
    metadata:
      labels:
        app: gatus-ingress-controller
    spec:
      serviceAccountName: gatus-ingress-controller
      containers:
        - name: manager
          image: ghcr.io/wihrt/gatus-ingress-controller:latest
          env:
            - name: INGRESS_CLASS
              value: traefik
            - name: TARGET_NAMESPACE
              value: gatus
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
