//go:build !ignore_autogenerated

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *GatusAlert) DeepCopyInto(out *GatusAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GatusAlert) DeepCopy() *GatusAlert {
	if in == nil {
		return nil
	}
	out := new(GatusAlert)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatusAlertList) DeepCopyInto(out *GatusAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatusAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatusAlertList) DeepCopy() *GatusAlertList {
	if in == nil {
		return nil
	}
	out := new(GatusAlertList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatusAlertSpec) DeepCopyInto(out *GatusAlertSpec) {
	*out = *in
}

func (in *GatusAlertSpec) DeepCopy() *GatusAlertSpec {
	if in == nil {
		return nil
	}
	out := new(GatusAlertSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusAlertStatus) DeepCopyInto(out *GatusAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatusAlertStatus) DeepCopy() *GatusAlertStatus {
	if in == nil {
		return nil
	}
	out := new(GatusAlertStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusAlertRef) DeepCopyInto(out *GatusAlertRef) {
	*out = *in
}

func (in *GatusAlertRef) DeepCopy() *GatusAlertRef {
	if in == nil {
		return nil
	}
	out := new(GatusAlertRef)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusDNSConfig) DeepCopyInto(out *GatusDNSConfig) {
	*out = *in
}

func (in *GatusDNSConfig) DeepCopy() *GatusDNSConfig {
	if in == nil {
		return nil
	}
	out := new(GatusDNSConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusUIConfig) DeepCopyInto(out *GatusUIConfig) {
	*out = *in
}

func (in *GatusUIConfig) DeepCopy() *GatusUIConfig {
	if in == nil {
		return nil
	}
	out := new(GatusUIConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusEndpoint) DeepCopyInto(out *GatusEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GatusEndpoint) DeepCopy() *GatusEndpoint {
	if in == nil {
		return nil
	}
	out := new(GatusEndpoint)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatusEndpointList) DeepCopyInto(out *GatusEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatusEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatusEndpointList) DeepCopy() *GatusEndpointList {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatusEndpointSpec) DeepCopyInto(out *GatusEndpointSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]GatusAlertRef, len(*in))
		copy(*out, *in)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(GatusDNSConfig)
		**out = **in
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(GatusUIConfig)
		**out = **in
	}
}

func (in *GatusEndpointSpec) DeepCopy() *GatusEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GatusEndpointStatus) DeepCopyInto(out *GatusEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatusEndpointStatus) DeepCopy() *GatusEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointStatus)
	in.DeepCopyInto(out)
	return out
}
